service: serverless-plugin-typescript-example

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false

functions:
  createPost:
    events:
      - http:
          method: post
          path: posts
          cors: true
    handler: src/index.createPost

  getPost:
    events:
      - http:
          method: get
          path: posts/{id}
          cors: true
    handler: src/index.getPost

  getAllPost:
    events:
      - http:
          method: get
          path: posts
          cors: true
    handler: src/index.getAllPost

  updatePost:
    events:
      - http:
          method: put
          path: posts/{id}
          cors: true
    handler: src/index.updatePost

  deletePost:
    events:
      - http:
          method: delete
          path: posts/{id}
          cors: true
    handler: src/index.deletePost
