service: serverless-plugin-typescript-example

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false

functions:
  createPost:
    events:
      - http:
          method: post
          path: post
          cors: true
    handler: src/index.createPost

  hello:
    events:
      - http:
          method: get
          path: hello
          cors: true
    handler: src/index.hello
